---

pipeline:
  account: att-dev-llabs-io
  application: afp
  location: afp-test
  name: dev-scep

private:
  - moniker: &moniker
      app: afp
      cluster: afp-scep-service
      detail: service
      stack: scep

chute:
  template: pipeline
  docker_images: &docker_images
    - name: locationlabs/cf_scep_service
      account: docker-luft-avast-com
  enable_triggers: true
  trigger_tag_regex: ^[1-9][0-9]*[-][0-9a-f]{6,8}$
  git_repo_name: ring.admin
  primary_git_branch: master
  helm_account: helm-ida-artifactory-dev

  helm_charts:
    - name: scep
      bake_stage_name: scep bake
      deploy_stage_name: scep deploy
      docker_images: *docker_images
      moniker: *moniker
      values_files:
        - path: helm_values/att.kube.dev.llabs.io/afp-test/values.yaml
        - path: helm_values/att.kube.dev.llabs.io/afp-test/scep/values.yaml
      bake_refId: '1'
      bake_requisiteStageRefIds: []
      deploy_refId: '2'
      deploy_requisiteStageRefIds:
        - '1'
